In [25]:
import pandas as pd
import numpy as np
from pct.tree.heuristic.Heuristic import Heuristic5
from pct.tree.heuristic.NumericHeuristicCopy1 import NumericHeuristic5
from pct.tree.splitter.splitterCopy1 import Splitter
from pct.tree.treeCopy1 import Tree
#from pct.tree.tree import Tree
#from pct.tree.treethreshold import Tree
# from pct.tree.ftest.ftest import FTest

## From YXH's data process

In [27]:

from sklearn.preprocessing import LabelEncoder

# Load the u.data dataset
u_data = pd.read_csv('u.data', sep='\t', header=None, names=['user_id', 'item_id', 'rating', 'timestamp'])

# # # Perform label encoding on user_id and item_id
# user_encoder = LabelEncoder()
# item_encoder = LabelEncoder()

# u_data['user_id'] = user_encoder.fit_transform(u_data['user_id'])
# u_data['item_id'] = item_encoder.fit_transform(u_data['item_id'])

# # # Create the rating matrix
# n_users = u_data['user_id'].nunique()
# n_items = u_data['item_id'].nunique()

# Define the threshold
THRESHOLD = 3  # Ratings above this are "Lovers", below are "Haters"

# Pivot the data
rating_matrix = u_data.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
rating_matrix.index = u_data['user_id'].unique()  # Ensure user_id alignment
rating_matrix.columns = u_data['item_id'].unique()  # Ensure item_id alignment


# Apply threshold classification to the rating matrix (after thresholding)
rating_matrix_thresholded = np.where(rating_matrix > THRESHOLD, 1, np.where(rating_matrix > 0, 0.5, 0))

# Convert numpy array to pandas DataFrame for easier inspection
rating_matrix_thresholded_df = pd.DataFrame(rating_matrix_thresholded)

rating_matrix_thresholded_df.index = u_data['user_id'].unique()  # Ensure user_id alignment
rating_matrix_thresholded_df.columns = u_data['item_id'].unique()  # Ensure item_id alignment

In [29]:
u_data

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [4]:
rating_matrix

,242,302,377,51,346,474,265,465,451,86,...,1594,1626,1645,1659,1682,1674,1640,1637,1630,1641
196,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
186,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
166,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
936,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
930,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
920,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## initiate tree and splitter

In [7]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


tree = Tree(min_instances=7)
tree.fit(rating_matrix, u_data['rating'], target_weights=None)

✅ Converted x and y to DataFrame
✅ Assigned x and y
✅ Creating target weights...
✅ Identifying numerical and categorical attributes...
✅ Creating Splitter...
Initializing Splitter...
✅ Calling build()...
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  471
👥 Users who rated item 471: 429
❤️ Lovers: 228
💔 Haters: 201
❓ Unknowns: 514
🔄 Recursively building tree for subsets...
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  231
👥 Users who rated item 231: 91
❤️ Lovers: 53
💔 Haters: 38
❓ Unknowns: 137
🔄 Recursively building tree for subsets...
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  202
👥 Users who rated item 202: 17
❤️ Lovers: 13
💔 Haters: 4
❓ Unknowns: 36
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  260
👥 Users who rated item 260: 12
❤️ Lovers: 6
💔 Haters: 6
❓ Unknowns: 26
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  153
👥 Users who rated item 153: 86
❤️ Lovers: 68
💔 Haters: 18
❓ Unknowns: 51
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  264
👥 Users who rated item 264: 131
❤️ Lovers: 65
💔 Haters: 66
❓ Unknowns: 70
🔄 Recursively building tree for subsets...
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  402
👥 Users who rated item 402: 38
❤️ Lovers: 16
💔 Haters: 22
❓ Unknowns: 27
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  1016
👥 Users who rated item 1016: 29
❤️ Lovers: 12
💔 Haters: 17
❓ Unknowns: 37
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  408
👥 Users who rated item 408: 50
❤️ Lovers: 34
💔 Haters: 16
❓ Unknowns: 20
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  412
👥 Users who rated item 412: 83
❤️ Lovers: 72
💔 Haters: 11
❓ Unknowns: 431
🔄 Recursively building tree for subsets...
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  408
👥 Users who rated item 408: 45
❤️ Lovers: 26
💔 Haters: 19
❓ Unknowns: 27
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  154
👥 Users who rated item 154: 3
❤️ Lovers: 2
💔 Haters: 1
❓ Unknowns: 8
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🌲 Building predictive clustering tree...
🔍 Best item for splitting:  402
👥 Users who rated item 402: 215
❤️ Lovers: 83
💔 Haters: 132
❓ Unknowns: 216
🔄 Recursively building tree for subsets...
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
🍃 Reached max depth at depth 3. Stopping recursion.
Total Error (Criterion Value): None
✅ Tree built successfully!

In [9]:
tree.print_tree_structure()

Leaf Node: No
Depth: 0
Item_ID: 471
Total_Error: 93848.85858180528
Children:
    Leaf Node: No
    Depth: 1
    Item_ID: 231
    Total_Error: 28570.52752870808
    Children:
        Leaf Node: No
        Depth: 2
        Item_ID: 202
        Total_Error: 6190.888078275447
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
        Leaf Node: No
        Depth: 2
        Item_ID: 260
        Total_Error: 3956.0548348452376
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
        Leaf Node: No
        Depth: 2
        Item_ID: 153
        Total_Error: 12617.50296825391
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
    Leaf Node: No
    Depth: 1
    Item_ID: 264
    Total_Error: 25095.706727140314
    Children:
        Leaf Node: No
        Depth: 2
        Item_ID: 402
        Total_Error: 5914.745640642753
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
        Leaf Node: No
        Depth: 2
        Item_ID: 1016
        Total_Error: 8787.503141841637
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
        Leaf Node: No
        Depth: 2
        Item_ID: 408
        Total_Error: 5172.082240141553
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
    Leaf Node: No
    Depth: 1
    Item_ID: 412
    Total_Error: 30232.612631818025
    Children:
        Leaf Node: No
        Depth: 2
        Item_ID: 408
        Total_Error: 3923.834065262223
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
        Leaf Node: No
        Depth: 2
        Item_ID: 154
        Total_Error: 187.08333333333331
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
        Leaf Node: No
        Depth: 2
        Item_ID: 402
        Total_Error: 21453.383081252417
        Children:
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3
            Leaf Node: Yes
            Depth: 3

In [11]:
rating_matrix.sort_index(axis=1).sort_index(axis=0)

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
1,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,0.0,4.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,0.0,4.0,0.0,0.0,0.0,3.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,2.0,3.0,0.0,0.0,0.0,4.0,0.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,3.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
rating_matrix = rating_matrix.sort_index(axis=1).sort_index(axis=0) 
predict_scores = tree.predict(rating_matrix)
predict_scores_unrated = tree.predict_test(rating_matrix)

In [31]:
predict_scores_unrated

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
1,NaN,3.782609,3.961538,3.888889,3.750000,3.000000,NaN,3.00,4.50,4.400000,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.666667,3.0,3.0
2,NaN,3.708333,NaN,4.470588,3.785714,3.285714,NaN,5.00,3.50,4.571429,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.666667,3.0,3.0
3,NaN,NaN,NaN,4.470588,3.785714,3.285714,4.366197,5.00,3.50,4.571429,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.666667,3.0,3.0
4,NaN,3.285714,NaN,4.333333,3.833333,3.000000,NaN,3.00,4.00,NaN,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.000000,3.0,3.0
5,3.519231,3.466667,3.928571,3.937500,3.600000,3.285714,3.887324,2.75,3.75,4.315789,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,2.000000,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,3.594203,3.708333,3.862745,4.470588,3.785714,3.285714,4.366197,5.00,3.50,4.571429,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.666667,3.0,3.0
940,3.250000,NaN,NaN,4.200000,3.000000,3.750000,NaN,5.00,NaN,NaN,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.000000,3.0,3.0
941,3.294118,3.285714,NaN,4.333333,NaN,3.000000,NaN,3.00,4.00,4.000000,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.000000,3.0,3.0
942,3.594203,NaN,3.862745,4.470588,3.785714,3.285714,4.366197,5.00,3.50,4.571429,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.666667,3.0,3.0
943,NaN,NaN,3.862745,4.470588,3.785714,3.285714,4.366197,5.00,3.50,4.571429,...,4.0,1.0,1.0,4.0,3.0,4.0,3.0,1.666667,3.0,3.0

In [37]:
def get_top_n_df_for_all_users(pred_matrix: pd.DataFrame, N=5):
    """
    Generate Top-N item recommendations for all users based on a prediction matrix.

    Parameters:
    - pred_matrix: pd.DataFrame, prediction scores (e.g., from predict_test()), 
                   with users as rows and items as columns.
    - N: int, number of items to recommend per user.

    Returns:
    - pd.DataFrame with columns: user_id, top_1, top_2, ..., top_N
    """
    records = []

    for user_id in pred_matrix.index:
        user_pred = pred_matrix.loc[user_id]
        top_items = user_pred.dropna().sort_values(ascending=False).head(N)
        # Fill in missing values with NaN if less than N items
        row = [user_id] + list(top_items.index) + [np.nan] * (N - len(top_items))
        records.append(row)

    columns = ['user_id'] + [f'top_{i+1}' for i in range(N)]
    return pd.DataFrame(records, columns=columns)

In [41]:
top_n_df = get_top_n_df_for_all_users(predict_scores_unrated, N=10)

print(top_n_df)

     user_id  top_1  top_2  top_3  top_4  top_5  top_6  top_7  top_8  top_9  \
0          1    889   1090   1140    250   1169   1192    195   1250   1313
1          2   1275   1360    351    629    852    997   1250   1367   1183
2          3    676   1372   1176   1360   1169   1366   1367    694    903
3          4    817   1232   1270   1267    398   1570   1254    108   1253
4          5   1143   1250    437   1424    727   1523   1423    248    916
..       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
938      939    903   1366   1360   1539   1542    195    772    932    449
939      940    359    997    351   1423   1426    817    596   1054    837
940      941    895   1394    108   1409   1407   1168    604    936   1570
941      942    852   1619    343    772    361   1409   1080   1386    903
942      943   1250    628   1386    932   1026    594    135    889   1409

     top_10
0      1366
1       361
2      1192
3      1168
4       997
..      ...
938    1313
939     607
940     624
941    1090
942     797

[943 rows x 11 columns]